use_frameworks!

platform :ios, '11.0'

target 'ATAuthSDK_iOS_Example' do
  pod 'ATAuthSDK_iOS', :path => '../'

  target 'ATAuthSDK_iOS_Tests' do
    inherit! :search_paths

    
  end
  
  post_install do |installer|
    installer.pods_project.build_configurations.each do |config|
      config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
    end
  end
end
